/*
Authors:
- Iván Maldonado (Kikemaldonado11@gmail.com)
- Maria José Vera (nandadevi97816@gmail.com)

Developed at: November 2024
*/

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <expression.hpp>
#include <string> 

extern FILE* yyin;
extern int yyparse();
extern Expression* parser_result;

// Usage function
void usage(char* argv[])
{
    printf("Usage: %s input_file\n", argv[0]);
    exit(1);
}

// Return the name of the input file passed as parameter
std::string get_output_name(char* argv[])
{
    std::string input_name = argv[1];
    int pos = input_name.find(".");

    return input_name.substr(0, pos);
}



int main(int argc, char* argv[])
{
    if (argc != 2)
    {
        usage(argv);
    }

    yyin = fopen(argv[1], "r");

    if (!yyin)
    {
        printf("Could not open %s\n", argv[1]);
        exit(1);
    }


    // Get output filename
    std::string output_name = get_output_name(argv); 

    // Parse file content
    int result = yyparse();


    if (result == 0)
    {
        std::string output;
        output = parser_result->eval();  
        
        // DEBUG purposes
        //printf("%s\n", output.c_str());

        // Create output file

        FILE* outputFile = fopen((output_name + "_output.txt").c_str(), "w");
        if (!outputFile)
        {
            printf("Error opening file for writing\n");
            exit(1);
        }

        fprintf(outputFile, "%s\n", output.c_str());
        fclose(outputFile);

    
        // Use pdflatex to generate a pdf from the output file

        std::string command = "pdflatex -jobname=" + output_name + " -" + output_name + "-directory=. " + output_name + "_output.txt";
        int result = system(command.c_str());

        result = system(command.c_str());


        if (result == -1) {
        fprintf(stderr, "Error running pdflatex\n");
        return 1;
        }
       

        // Delete extra files generated by pdflatex
        command = "rm " + output_name + ".aux " + output_name + ".log " + output_name + ".toc";
        system(command.c_str());

        parser_result->destroy();
    }
    else
    {
        printf("Parse failed!\n");
    }

    return 0;
}